### ISSUE TITLE
 DataSource in DropDown isn't working

### ISSUE THREAD

**Issue by TranThiNgocHa** [haxeui/haxeui-core#246] opened 2018-12-26 08:59 UTC
my code :
![image](https://user-images.githubusercontent.com/46014506/50440047-f4ae9480-0926-11e9-8b6f-c70c57524d89.png)
this is a result : 
![image](https://user-images.githubusercontent.com/46014506/50440069-13149000-0927-11e9-8674-5b3ff5a636db.png)
how can i use dataSource and dropdown ?

**Comment by ianharrigan** [comment] 2018-12-26 10:00
Hmmm, that should work... What branch are you using? Master? Which backend? (thought it shouldnt make a difference)

Cheers,
Ian

**Comment by TranThiNgocHa** [comment] 2018-12-26 10:13
yes, i'm using branch Master, i'm trying to compile to js and html5 and it's working with ListView but DropDown is not working

**Comment by ianharrigan** [comment] 2018-12-26 10:42
Which backend are you specifically using? haxeui-core + haxeui-openfl? haxeui-html5? Ive tried it this end and it seems to work...

**Comment by TranThiNgocHa** [comment] 2018-12-26 10:49
i'm using only haxeui-core, Is it not working because without haxe openfl ?, i'm learning Haxe

**Comment by ianharrigan** [comment] 2018-12-26 11:03
Can you .zip up your project so i can take a look?

Thanks.

**Comment by TranThiNgocHa** [comment] 2018-12-27 01:17
ok, this is my project, thanks you for take care of my issue
[New Drop Down.zip](https://github.com/haxeui/haxeui-core/files/2711125/New.Drop.Down.zip)

**Comment by TranThiNgocHa** [comment] 2018-12-27 02:59
oh, i found my issue, this position is hiding data when i click dropdown, thanks u so much ian harrigan

**Comment by ianharrigan** [comment] 2018-12-27 06:38
Hmm, ok, yes, thats interesting. I still feel like its a bug, but yes you are right, moving it to position 100, 100 means it appears correctly - ill investigate and fix.

Cheers,
Ian

**Comment by ianharrigan** [comment] 2018-12-27 06:53
Ok, ive found the "problem"... the issue is that the page that contains that haxeui application in your project doesnt have a "size" set. So what is happening is the dropdown is added to the "screen" (which for haxeui-html5 is the webpage), then when it its clicked it tried to show its dropdown, but it does have enough space, so it makes the dropdown show up (instead of down) so you cant see it. The best way to fix this is to add this to the .html file:

```html
<style>
    * {
        box-sizing: border-box;
    }

    html {
        margin: 0;
        width: 100%;
        height: 100%;
    }

    body {
        font-family: 'Arial';
        font-size: 13px;
        margin: 0;
        width: 100%;
        height: 100%;
    }
</style>
```

**Comment by TranThiNgocHa** [comment] 2018-12-27 10:15
thanks u so much, i will try it after complete my project, i will reply u as soon as possible

**Comment by TranThiNgocHa** [comment] 2019-01-28 07:59
hey, it's worked, u can close this issue now

**Comment by ianharrigan** [comment] 2019-01-30 11:06
great, thanks!

**Closed by ianharrigan** 2019-01-30 11:06 UTC
Labels: retest required
