### ISSUE TITLE
removeComponent, removeAllComponents doesnt work

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#23] opened 2016-09-06 21:50 UTC
This may be related to #12 
A dynamically added component cant be removed.  I did not look into xml based creations.  I tested in html5, nme (flash and CPP).

Clicking the click me button twice will cause browser to hang since .

## Expected Behavior
I would expect that the number of childComponents would be reduced immediately if removeComponent(component) is called

## Current Behavior
childComponents.length remains the same. For example 1 before removal and 1 after

## Test app / minimal test case
Attaching sample project
[Small.zip](https://github.com/haxeui/haxeui-core/files/457862/Small.zip)

**Comment by ianharrigan** [comment] 2016-09-07 09:13
OK, i can see what the issue is here. Its because you are using:

```xml
<scrollview>
</scrollview>
```

Then later trying to add vbox to it as an item, however, the first `Box` will be used for the scrolling content. So this is what causes the problem. A simple fix is to change it to:

```xml
<scrollview>
    <vbox />
</scrollview>
```

This then sets your content to be ready (if you wanted horizontal scrolling use an `HBox`). In the mean time ill try and think of a suitable way to have the VBox added automatically.

**Comment by ianharrigan** [comment] 2016-09-07 11:15
Ok, this should be fixed now. Can you retest and close if all ok?

Now things have changed, you no longer _ever_ need to add a `VBox`, `HBox` etc, so you only add children you want in the actual content of the item. If you do want a horizontal layout you use the new `layout` property (defaults to `"vertical"`), eg:

```xml
<scrollview layout="horizontal">
    <button text="Button" />
    <button text="Button" />
    <button text="Button" />
</scrollview>
```

**Closed** 2016-09-08 00:08 UTC
Labels: bug, retest required
