### ISSUE TITLE
.htmlText doesn't change font size and applies bold to the entire label text since 1.2.0

### ISSUE THREAD

**Issue by Gulvan0** [haxeui/haxeui-core#390] opened 2021-05-31 09:44 UTC
Labels got several display bugs on OpenFL after I updated the haxeui lib to 1.2.3.

## Code to Reproduce
```
var l:Label = new Label();
l.text = "Challenge by";
//l.width = 800;
addChild(l);
```

## Expected Behavior
1. Label displaying "Challenge by" text;
2. Changing the width has no side effects

## Current Behavior
1. Label displays the strange ligature instead of text specified;
2. Changing the width compile-time or run-time makes the label disappear completely

Both invalidate() and invalidateComponent() have no effect. Changing .htmlText instead of .text doesn't work. Using Screen.instance.addComponent() instead of addChild() changes nothing. 

In the real app, some of the labels vanished, while the style of others was reset to default. Neither using the combination of .text and .style properties nor setting the font size/bold flag by tags in .htmlText worked.

## Media
![image](https://user-images.githubusercontent.com/16256911/120175438-e4ddbd80-c20e-11eb-8b23-eed4db30d87a.png)

## Your Environment
* HaxeUI version: 1.2.3 and 1.2.0
* HaxeUI backend: OpenFL
* OpenFL version: 9.1.0 (latest)
* Lime version: 7.9.0 (latest)
* Haxe version: 4.2.2
* Browser: Chrome 91
* Operating System: Windows 10
* Link to your project: https://github.com/Gulvan0/Intellector

**Comment by ianharrigan** [comment] 2021-05-31 13:02
hmmm, that seems odd... any chance you could try the git version of haxeui-core and haxeui-openfl?

**Comment by Gulvan0** [comment] 2021-05-31 14:58
> hmmm, that seems odd... any chance you could try the git version of haxeui-core and haxeui-openfl?

Just tried it, still getting the same results

**Comment by ianharrigan** [comment] 2021-05-31 15:37
any chance you can knock up a minimal example? The linked project is hard to run - i managed to get the server running (but had to edit the code to do so) and the client still says it can connect  - so it would be easier to diagnose what the issue is if there is just a test project with just the issue and not the whole server / client architecture. 

Cheers,
Ian

**Comment by Gulvan0** [comment] 2021-05-31 15:40
Of course, here is the example from the beginning of the post
[Testing.zip](https://github.com/haxeui/haxeui-core/files/6571242/Testing.zip)

**Comment by ianharrigan** [comment] 2021-05-31 15:49
Im not sure if its just an issue with your test app, but did you init haxeui with:

```haxe
Toolkit.init();
```

When i add that line before anything else, like so:
```haxe
Toolkit.init();
var firstLabel:Label = new Label();
firstLabel.htmlText = "Challenge by";
firstLabel.x = 200;
Screen.instance.addComponent(firstLabel);
```
Then everything is fine, but i wonder if that is just your test app that missing that line?

**Comment by Gulvan0** [comment] 2021-05-31 15:53
> Im not sure if its just an issue with your test app, but did you init haxeui with:
> 
> ```hx
> Toolkit.init();
> ```
> 
> When i add that line before anything else, like so:
> 
> ```hx
> Toolkit.init();
> var firstLabel:Label = new Label();
> firstLabel.htmlText = "Challenge by";
> firstLabel.x = 200;
> Screen.instance.addComponent(firstLabel);
> ```
> 
> Then everything is fine, but i wonder if that is just your test app that missing that line?
> 
> ![image](https://user-images.githubusercontent.com/3024242/120217510-bb398c00-c238-11eb-804e-618e8fa88590.png)

Whoopsie, my bad, let's move on to the real issue

Consider changing the Main's constructor body this way:
```
        super();
        Toolkit.init();
        var firstLabel:Label = new Label();
        firstLabel.htmlText = "<b>Challenge</b> by";
        firstLabel.x = 200;
        Screen.instance.addComponent(firstLabel);
```

Notice that "by" appears bold as well

**Comment by Gulvan0** [comment] 2021-05-31 15:55
Then, change the .htmlText value like this:
`firstLabel.htmlText = '<font size="16">Challenge by</font>';`

You will see that the formatting had no effect

**Comment by ianharrigan** [comment] 2021-05-31 16:11
i think this might be an openfl issue, i just tried:

```haxe
        var tf = new TextField();
        tf.htmlText = '<font size="26"><b>Challenge</b> by</font>';
        Lib.current.stage.addChild(tf);
```

and i get:

![image](https://user-images.githubusercontent.com/3024242/120219508-a0b4e200-c23b-11eb-8fd8-dc9edac6ad62.png)

(the top left one is the raw openfl textfield - and it appears to be all bold too, openfl also seems to do something odd with the sizing - the font size does appear to be something with haxeui though) 

Ill pull and build latest openfl, maybe something has changed there?

**Comment by ianharrigan** [comment] 2021-05-31 16:30
OK, so about the `.style` one, you need to use `.customStyle`, `.style` is what haxeui uses for the "final" style of the component, so any changes you make there will be overwritten. This is the first time this has happened (the confusion), and i think the naming here is especially bad, so pretty soon `.style` will become `.computedStyle` (and probably makes sense for it to be private too if possible) and `.customStyle` will become `.style`

**Comment by ianharrigan** [comment] 2021-05-31 16:52
I opened this btw: https://github.com/openfl/openfl/issues/2498

**Comment by ianharrigan** [comment] 2021-05-31 18:26
(that openfl issue as just been fixed btw, so retest and see what haxeui issues - if any - are left over)

**Comment by Gulvan0** [comment] 2021-05-31 18:46
> OK, so about the `.style` one, you need to use `.customStyle`, `.style` is what haxeui uses for the "final" style of the component, so any changes you make there will be overwritten. This isnt the first time this has happened (the confusion), and i think the naming here is especially bad, so pretty soon `.style` will become `.computedStyle` (and probably makes sense for it to be private too if possible) and `.customStyle` will become `.style`

Great, that works, but I still need .htmlText because of the partial formatting. Is there any way to do it code-wise, like with styles? OpenFL TFs, for instance, have setTextFormat() that can accept optional startIndex and endIndex.

**Comment by ianharrigan** [comment] 2021-05-31 18:55
You can access the framework specific text field (openfl in this case) by using "getTextInput()" or "getTextDisplay()"... that will return the openfl textfield... it will be interesting how you would use that, it may be that haxeui will try to overwrite any changes you try to make to formatting there everytime you call ".invalidate()" (maybe we can add a flag or something)

The main issue with exposing a setTextFormat directly on a haxeui text input / area is no other backend framework is going to support those calls.

**Comment by Gulvan0** [comment] 2021-05-31 19:02
> You can access the framework specific text field (openfl in this case) by using "getTextInput()" or "getTextDisplay()"... that will return the openfl textfield... it will be interesting how you would use that, it may be that haxeui will try to overwrite any changes you try to make to formatting there everytime you call ".invalidate()" (maybe we can add a flag or something)
> 
> The main issue with exposing a setTextFormat directly on a haxeui text input / area is no other backend framework is going to support those calls.

Yeah, but I was asking whether there is a HaxeUI way to do partial formatting apart from using .htmlText which seems to be broken

**Comment by ianharrigan** [comment] 2021-05-31 19:04
> but I was asking whether there is a HaxeUI way to do partial formatting apart from using .htmlText

So the short answer there is no really - not in a univeral, backend agnostic way (in fact even htmlText isnt supported on most backends). 

> .htmlText which seems to be broken

What else is broken about htmlText?

**Comment by Gulvan0** [comment] 2021-05-31 19:07
> What else is broken about htmlText?

Just that, font size and partial formatting. My main reasons behind using it)

**Comment by ianharrigan** [comment] 2021-05-31 19:10
Right, so htmlText in openfl looks like its a little broken at the moment, maybe setTextFormat(...) too? No idea, i think i have noticed one thing in haxeui-openfl however that im looking at correcting now (its that haxeui labels setTextFormat and setDefaultTextFormat, i think it should only set the latter)

**Comment by ianharrigan** [comment] 2021-05-31 19:28
OK, so i have (i think) fixed a haxeui issue (latest git), consider:

```haxe
        var firstLabel:Label = new Label();
        firstLabel.htmlText = "<font size='60'>Challenge by</font> Bob <font size='10'>Barker</font>";
        firstLabel.customStyle = { fontSize: 18 };
        firstLabel.y = 20;
        firstLabel.x = 200;
        Screen.instance.addComponent(firstLabel);
```

before: 

![image](https://user-images.githubusercontent.com/3024242/120233570-6efd4480-c256-11eb-87a0-3e51222cd0ec.png)

after:

![image](https://user-images.githubusercontent.com/3024242/120233719-bc79b180-c256-11eb-8b8a-92eef9f73852.png)

Basically the issue was two fold, 1) that haxeui was using `setTextFormat` and therefore overwriting any previously formatted text formats (i presume) and 2) that it seems if you change the defaultTextFormat you need to reapply any htmlText in openfl

**Comment by Gulvan0** [comment] 2021-05-31 19:31
> OK, so i have (i think) fixed a haxeui issue (latest git), consider:
> 
> ```hx
>         var firstLabel:Label = new Label();
>         firstLabel.htmlText = "<font size='60'>Challenge by</font> Bob <font size='10'>Barker</font>";
>         firstLabel.customStyle = { fontSize: 18 };
>         firstLabel.y = 20;
>         firstLabel.x = 200;
>         Screen.instance.addComponent(firstLabel);
> ```
> 
> before:
> 
> ![image](https://user-images.githubusercontent.com/3024242/120233570-6efd4480-c256-11eb-87a0-3e51222cd0ec.png)
> 
> after:
> 
> ![image](https://user-images.githubusercontent.com/3024242/120233719-bc79b180-c256-11eb-8b8a-92eef9f73852.png)
> 
> Basically the issue was two fold, 1) that haxeui was using `setTextFormat` and therefore overwriting any previously formatted text formats (i presume) and 2) that it seems if you change the defaultTextFormat you need to reapply any htmlText in openfl

Really nice!
Does it work with bold as well?

**Comment by ianharrigan** [comment] 2021-05-31 19:32
pretty sure that is an openfl issue that is, essentially, outside of my control im afraid. Chris (from the linked issue) seems like hes spearheading the text impl in openfl recently, so i would guess that is the best issue to watch :)

**Comment by Gulvan0** [comment] 2021-05-31 19:33
> pretty sure that is an openfl issue that is, essentially, outside of my control im afraid. Chris (from the linked issue) seems like hes spearheading the text impl in openfl recently, so i would guess that is the best issue to watch :)

So... Closing now?

**Comment by ianharrigan** [comment] 2021-05-31 19:34
lets keep it open until you are happy its fixed and working, just in case there is another haxeui issue somewhere ;)

**Comment by Gulvan0** [comment] 2021-06-01 13:17
I'm happy, _I suppose_
![image](https://user-images.githubusercontent.com/16256911/120329726-cfdb5a00-c2f4-11eb-9366-21ad151528c4.png)

**Comment by ianharrigan** [comment] 2021-06-01 13:19
how come "i suppose"? Whats up with it?

**Comment by Gulvan0** [comment] 2021-06-01 13:27
> how come "i suppose"? Whats up with it?

Well, I can't be sure since, as I said, I don't use much of the Label's features, but as for the issues mentioned, all of them were successfully fixed, yay.

Though while writing this comment, I did notice one problem: paragraph alignment makes text disappear when align is set to "center" or "right" and, as for "justify", it works the same as "left". Not sure if I need to start another issue or keep this open.

Minimal example project: same
Main's constructor:
```
super();
Toolkit.init();
var firstLabel:Label = new Label();
firstLabel.htmlText = '<p><b>Gulvan:</b> pururu</p><p><b>Kaz:</b> pupu</p><p align="justify"><i>Spectator connected</i></p><p><b>Gulvan:</b> wow</p>';
firstLabel.customStyle = {fontSize: 16};
firstLabel.x = 200;
firstLabel.width = 600;
Screen.instance.addComponent(firstLabel);
```
![image](https://user-images.githubusercontent.com/16256911/120330931-f6e65b80-c2f5-11eb-9389-f2ec31740cc8.png)

**Comment by ianharrigan** [comment] 2021-06-01 13:35
I think you should try with "raw" openfl textfields, my guess is that it wont work there either... haxeui-openfl is essentially just setting the .htmlText of an openfl TextField.

If it doesnt work in "raw openfl" then my advice would be to append it to the openfl issue linked above.

**Comment by Gulvan0** [comment] 2021-06-01 13:35
> I think you should try with "raw" openfl textfields, my guess is that it wont work there either... haxeui-openfl is essentially just setting the .htmlText of an openfl TextField.
> 
> If it doesnt work in "raw openfl" then my advice would be to append it to the openfl issue linked above.

Ok, thanks. closing now? Every issue I noticed were addressed

**Comment by ianharrigan** [comment] 2021-06-01 13:36
OK, thats fine with me, just re-open (or recreate) if something else doesnt work

**Closed** 2021-06-01 13:37 UTC
Labels: requires investigation
