### ISSUE TITLE
Subclasses should automatically apply css classes

### ISSUE THREAD

**Issue by varadig** [haxeui/haxeui-core#126] opened 2017-04-20 09:22 UTC
I need to extend the Button control with some custom functionality:

```
package core.haxeui.controls;
import haxe.ui.components.Button;
import core.base.CoreClassFactory;
import core.base.CoreCallback;
import core.service.CoreService;

import core.context.CoreContext;
import core.notification.CoreNotification;
import core.service.CoreServiceContainer;
class GuiButton extends Button {
    public var sc:CoreServiceContainer;

    public var context:CoreContext;

    public var callbacks:Map<String, Array<CoreService>> = new Map();

    public function new() {
        super();
        CoreClassFactory.construct(this);
    }


    public function serviceAddCallback(params:Map<String, Dynamic>):Void {
        CoreClassFactory.serviceAddCallback(this, params);
    }

    public function serviceAddCallbacks(params:Map<String, Dynamic>):Void {
        CoreClassFactory.serviceAddCallbacks(this, params);
    }


    @protected function createCallBack(group:String):CoreCallback {
        return CoreClassFactory.createCallBack(this, group);
    }

    @protected function createNotificaionByName(name:String):CoreNotification {
        return this.sc.getService(CoreNotification.CREATE_NOTIFICATION)
        .addParam(CoreNotification.NAME, name)
        .execute();
    }

    @protected function log(message:Dynamic):Void {
        CoreClassFactory.log(this, message);
    }
}
```

Maybe I miss something, but when I wanted to add the custom button to stage i see just the button label:

```
package;


import haxe.ui.components.Button;
import core.display.CoreSprite;
import core.haxeui.controls.GuiButton;
import haxe.ui.core.ComponentClassMap;
import haxe.ui.Toolkit;



class Main extends CoreSprite {


    public function new() {

        super();
        ComponentClassMap.register("guiButton", 'core.haxeui.controls.GuiButton');
        Toolkit.init();
        var b1:GuiButton = new GuiButton();
        b1.text = "GuiButton";
        b1.x = 100;
        b1.y=100;
        this.addChild(b1);

        var b2:Button= new Button();
        b2.text = "Button";
        b2.x = 300;
        b2.y=100;
        this.addChild(b2);
    }
}
```

![screen shot 2017-04-20 at 11 17 54](https://cloud.githubusercontent.com/assets/6317148/25223505/d6883b3c-25bb-11e7-9e98-00fa0f3aafe2.png)

**Comment by ianharrigan** [comment] 2017-04-20 09:48
I think the answer might be this: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/components/DropDown.hx#L23

**Comment by varadig** [comment] 2017-04-20 09:51
Thanks, it's work ;)

**Comment by ianharrigan** [comment] 2017-04-20 09:54
Reopening:

As a note (for when i come round to this issue in case the line numbers change):

The issue is that you have to explicitly add CSS classes to components that extend others, example:

```haxe
MyButton extends Button {
    public function new() {
        super();
        addClass("button"); // TODO: shouldnt have to do this
        addClass("mybutton"); // TODO: shouldnt have to do this
    }
}
```

The fix would be that, somehow, the constructor (or somewhere) should be able to add all the appropriate css classes automatically, eg:

MyOtherButton -> MyButton -> Button -> Component

In that example, `MyOtherButton` should have the css classes `myotherbutton`, `mybutton`, `button`, `component`

**Comment by ianharrigan** [comment] 2017-04-20 10:01
Code to achieve this:

```haxe
        var m = new MyButton();
        var c:Class<Dynamic> = Type.getClass(m);
        while (c != null) {
            var css = Type.getClassName(c);
            trace(css.split(".").pop().toLowerCase());
            c = Type.getSuperClass(c);
        }
```

**Comment by ianharrigan** [comment] 2017-05-24 17:33
This should be fixed now, can you possibly retest?

Cheers,
Ian

**Closed** 2020-10-29 18:04 UTC
Labels: bug
