### ISSUE TITLE
Adding propagation stop on onClick events

### ISSUE THREAD

**Issue by ibilon** [haxeui/haxeui-core#4] opened 2016-07-21 15:14 UTC
## Expected Behavior

Adding a `stopPropagation():Void` function to UIEvent (I guess) that'll prevent the event from reaching another component higher in the parenting chain.
## Current Behavior

Currently when clicking on a component its parent will also receive the onClick event without possibility to stop it.

Not sure if the parent's parent also receive the event and if this only apply to components or containers also.
## Context

Using this to let the user select a component to edit its properties,
currently the event will be received on the topmost parent last and it'll be like the user missed.

**Comment by ibilon** [comment] 2016-07-21 19:45
Looked more into this,
the event doesn't move up to the parent, it's actually that each component _generates_ an event.

So I don't think this will be possible.

**Comment by ianharrigan** [comment] 2016-07-21 19:54
Test code to reproduce the problem:

```html
<?xml version="1.0" encoding="utf-8"?>
<vbox id="main">
    <script>
        function testButton1Click() {
            testButton1.text = "This shouldnt happen if you clicked TEST!";
        }
    </script>

    <hbox>
        <button id="testButton1" styleNames="big-button" text="Click Me!" onClick="testButton1Click()" width="400">
            <button text="TEST" />
        </button>
    </hbox>
</vbox>
```

**Comment by ianharrigan** [comment] 2016-07-22 00:42
One thing to think about in the commit above is the removal of `mouseChildren`. The reason that was put in was so that haxeui composite `Label` components wont get events. It might no longer be needed, or might have been ill conceived to start with. But for now its commented out rather than removed.

**Comment by ianharrigan** [comment] 2016-07-22 08:21
Ive also just noticed that the fix i supplied only applies to `haxeui-openfl`, will leave this issue open with checklist to ensure all backends are fixed before closing:

- [x] haxeui-openfl
- [ ] haxeui-flambe
- [ ] haxeui-kha
- [ ] haxeui-html5
- [ ] haxeui-pixijs
- [ ] haxeui-nme
- [ ] haxeui-luxe
- [ ] haxeui-hxwidgets

**Closed** 2020-10-29 18:18 UTC
Labels: bug
