### ISSUE TITLE
Label display missing text if contains \n

### ISSUE THREAD

**Issue by hypergeome** [haxeui/haxeui-core#391] opened 2021-06-07 04:03 UTC
When we set text for label that contains \n, the last line wont be displayed

## Expected Behavior

When setting text for label that contains \n, all lines should be displayed.
## Current Behavior

When we set text for label that contains \n, the last line wont be displayed

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Gulvan0** [comment] 2021-06-18 21:35
@ianharrigan As far as I know, the problem is that label does display only the text on the first line, but not the others. This applies to both the usage of a newline symbol (the case described above) AND just an automatic word wrapping.

This is broken since 1.2.0.

This also affects Dialogs.

I think, this is a critical bug

**Comment by ianharrigan** [comment] 2021-06-19 05:51
Hmm, missed this somehow... Have you tried git versions? Still an issue there?

**Comment by ianharrigan** [comment] 2021-06-19 05:52
Also, what backend is this etc?

**Comment by Gulvan0** [comment] 2021-06-19 09:14
> Hmm, missed this somehow... Have you tried git versions? Still an issue there?

> Also, what backend is this etc?

Ah, sorry, I forgot to add these details.

Yeah, so my version is git and my backend is haxeui-openfl.

**Comment by ianharrigan** [comment] 2021-06-19 09:38
This looks to be openfl related, im going to work around in for now in haxeui-openfl, but ive also opened an issue here: https://github.com/openfl/openfl/issues/2499

**Comment by Gulvan0** [comment] 2021-06-19 09:40
> This looks to be openfl related, im going to work around in for now in haxeui-openfl, but ive also opened an issue here: [openfl/openfl#2499](https://github.com/openfl/openfl/issues/2499)

Thank you very much!

**Comment by ianharrigan** [comment] 2021-06-19 09:47
OK, that should be "fixed" now (just worked around it for now, but hopefully openfl will fix the underlying issue)

![image](https://user-images.githubusercontent.com/3024242/122638400-2b2e8a00-d0f4-11eb-907d-8956c307af2b.png)

**Comment by Gulvan0** [comment] 2021-06-19 10:19
> OK, that should be "fixed" now (just worked around it for now, but hopefully openfl will fix the underlying issue)
> 
> ![image](https://user-images.githubusercontent.com/3024242/122638400-2b2e8a00-d0f4-11eb-907d-8956c307af2b.png)

Yay, this has definitely been fixed, both for labels and for dialogs. Thanks a lot! Closing now (as this is the openfl-only issue now)?

**Comment by ianharrigan** [comment] 2021-06-19 10:27
Yeah, might as well close this... the workaround isnt awful, and if / when openfl fixes it we can just remove the `+1'

**Closed by ianharrigan** 2021-06-19 10:27 UTC
Labels: external framework related, retest required
