### ISSUE TITLE
Can't find a way to calculate remaining space...

### ISSUE THREAD

**Issue by ArgosOz** [haxeui/haxeui-core#190] opened 2017-11-16 13:07 UTC
Let's say... 

- Width of the window is 900 pixels 
- and I use all of it with hboxContainer 
- then I set vboxLeft's width in pixels 
- and now I need to calculate the remaining space for vboxRight.

What are my rather cross platform options?  
Is there a way to recalculate vboxRight width as the window width changes?

~~~~
<hbox id="hboxContainer" width="100%">
    <vbox id="vboxLeft" width="540px">
        <button text="Hello" />
    </vbox>
    <vbox id="vboxRight" width="*">
        <button>World</button>
    </vbox>
</hbox>
~~~~

**Comment by ibilon** [comment] 2017-11-16 13:09
iirc you can do "100%" which doesn't mean the width of the parent but 100% of the remaining space.

**Comment by ArgosOz** [comment] 2017-11-16 13:31
@ibilon I set bg color green... `vboxRight.backgroundColor = 0x00FF00;` but I can't see it because vboxRight shrink wraps the button as far as I can see. 

Below is the result of `<vbox id="vboxRight" width="100%">`

![screenshot](https://user-images.githubusercontent.com/3820883/32893471-a9d5ebfa-caea-11e7-8e7c-4263898b839c.png)

When I set it `<vbox id="vboxRight" width="180px">` for example... I get this:

![screenshot](https://user-images.githubusercontent.com/3820883/32893614-3f84182a-caeb-11e7-9882-c98383bce49e.png)


I need the button to take up the available width.
￼

**Comment by ianharrigan** [comment] 2017-11-17 11:07
This works fine for me:

```
<hbox id="hboxContainer" width="100%" style="background-color: red; padding: 5px;">
    <vbox id="vboxLeft" width="540px" style="background-color: green;">
        <button text="Hello" />
    </vbox>
    <vbox id="vboxRight" width="100%" style="background-color: blue">
        <button>World</button>
    </vbox>
</hbox>
```

![image](https://user-images.githubusercontent.com/3024242/32944405-c40c32ae-cb8f-11e7-9378-e755d057c8bd.png)

Note, i added the padding to hboxContainer just so you can see it. 

So im not sure if im missing something or not understand what you are trying to do?

**Comment by ianharrigan** [comment] 2017-11-17 11:09
This also works as expected:

```xml
<hbox id="hboxContainer" width="100%" style="background-color: red; padding: 5px;">
    <vbox id="vboxLeft" width="540px" style="background-color: green;">
        <button text="Hello" />
    </vbox>
    <vbox id="vboxRight" width="100%" style="background-color: blue">
        <button width="100%">World</button>
    </vbox>
</hbox>
```

![image](https://user-images.githubusercontent.com/3024242/32944538-279aa882-cb90-11e7-8820-8b4526e13442.png)

**Comment by ArgosOz** [comment] 2017-11-17 12:31
@ianharrigan Thanks.

I believe something wrong with my hello world app because I can't get the same result.

Could you please look at it and tell me what's wrong?

[HaxeUI.zip](https://github.com/haxeui/haxeui-core/files/1482273/HaxeUI.zip)

**Comment by ianharrigan** [comment] 2017-11-17 12:47
Ok, so the issue is that you are using a custom component and not giving it any dimensions.

```xml
<?xml version="1.0" encoding="utf-8"?>
<vbox width="100%">
	<style source="../css/main.haxeui.css" />

	<label text="Hello world" />
	<image resource="../assets/img/haxeui.png" />

	<CustomView width="100%" />
</vbox>
```

The first thing is that the root vbox didnt have a width (things default to size `auto`- which means it will be the size of the children - however, if one of those children is % then it doesnt know how to calculate it because the parent is supposed to be the size of the children and it cant know a % of an autosize)

The second issue is that the custom component itself didnt have a width either, so the same thing applies there. Basically:

```
vbox <--- width is auto
   CustomView <--- width is auto
       vbox % <--- no way to know this % width, % of auto? 
```

compared to:

```
vbox <--- width is a % or fixed - cool, we can calc
   CustomView <--- width is a % or fixed - cool, we can calc
       vbox % <--- width is a % or fixed - cool, we can calc
```

That make sense?

**Comment by ArgosOz** [comment] 2017-11-17 12:51
@ianharrigan 100% :) Thanks.

**Comment by ianharrigan** [comment] 2017-11-17 12:53
Also, btw, put this is the index.html somewhere (head / body), etc:

```html
    <style>
        * {
            box-sizing: border-box;
        }
    </style>
```

This will make everything line up correctly and look "right"... eventually haxeui will do this automatically for you, but for now it has to be done manually.

**Comment by ArgosOz** [comment] 2017-11-17 12:54
Ok. I will.

**Comment by ianharrigan** [comment] 2017-11-17 13:03
Can you close this if you are happy with it all working as expected? 

Cheers.

**Closed** 2017-11-17 13:04 UTC
Labels: question
