### ISSUE TITLE
Massive scrollbar arrows!!

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#72] opened 2016-12-29 00:57 UTC
Is issue in NME and HTML so I assume all.  So for the all caps in the image I didn't feel like changing it

## Media
![image](https://cloud.githubusercontent.com/assets/2074385/21534620/941c92b6-cd1e-11e6-98d2-a163f2f275ca.png)

## Test app / minimal test case
[Full.zip](https://github.com/haxeui/haxeui-core/files/676456/Full.zip)

**Comment by ianharrigan** [comment] 2016-12-29 08:30
Haha... indeed very strange! Will check it out... no doubt something simple.

**Comment by ianharrigan** [comment] 2016-12-29 09:31
So thats really strange... Your "blissel.png" is interfering somehow

**Comment by ianharrigan** [comment] 2016-12-29 09:41
Ok, the issue is here:

```css
#column1, column2{
	width:180;
	padding:0;
}
```

the `column2` doesnt have a `#` in front of it, so it applying that to everything for some reason.

**Comment by ianharrigan** [comment] 2016-12-29 09:48
Should be fixed now... Can you retest and close and required? Thanks.

**Closed** 2016-12-29 19:27 UTC
Labels: bug, requires investigation, retest required
