### ISSUE TITLE
Image does not scale when placed in second tab of tabview

### ISSUE THREAD

**Issue by x2f** [haxeui/haxeui-core#217] opened 2018-02-28 03:23 UTC
On Windows (neko) with Haxe 3.4.6 and using the haxeui git version e572ff0e8001a188d43880482a2a39a71ea6154f (along with openfl 7.1.2 and latest git haxeui-openfl https://github.com/haxeui/haxeui-openfl/commit/3db0874071e8469c105d22b234798ce30f4bc7e4) 

Placing a PNG image in both tabs of a TabView (each within an absolute container), both with the same size (150x150) for a (64x64) image, result in different sizes shown on screen. The image on the first tab is 150x150, and the image on the second tab has its original 64x64 size. Normally, the image should be 150x150 on both tabs.

The same issue exists for other image sizes and for growing or shrinking the image. I think it also happens with Haxe 3.4.7.

```
class Main extends Sprite {

  public function new () {
    super ();
    Toolkit.init();

    var main = new Absolute();
    main.height = Screen.instance.height ;
    main.width = Screen.instance.width;

    var tabView2 = new TabView();
    tabView2.x = 450;
    tabView2.y = 350;
    tabView2.width = 200;
    tabView2.height = 200;

    var abs2 = new Absolute();
    abs2.percentWidth = 100;
    abs2.percentHeight = 100;
    abs2.text = 'First';
    var icon4 = new Image();
    icon4.resource = "assets/images/a_64_by_64_image.png";
    icon4.width = 150;
    icon4.height = 150;
    abs2.addComponent(icon4);
    tabView2.addComponent(abs2);

    var abs3 = new Absolute();
    abs3.percentWidth = 100;
    abs3.percentHeight = 100;
    abs3.text = 'Second';
    var icon3 = new Image();
    icon3.resource = "assets/images/a_64_by_64_image.png";
    icon3.width = 150;
    icon3.height = 150;
    abs3.addComponent(icon3);
    tabView2.addComponent(abs3);

    main.addComponent(tabView2);

    Screen.instance.addComponent(main);
  }

```
```
$ haxelib list
haxeui-core: 0.0.3 [git]
haxeui-openfl: [git]
hscript: [2.1.1]
lime: 2.9.1 [6.2.0]
openfl: 3.6.1 [7.1.2]
```

**Comment by ianharrigan** [comment] 2018-02-28 07:49
Thanks looks like a pretty strange one - will look into it.

**Comment by ianharrigan** [comment] 2019-12-10 17:27
Im cleaning issues, retested this for sanity and behaviour seems to be expected behaviour, so am closing.

Feel free to open another issue if problem persists.

Thanks!
Ian

**Closed by ianharrigan** 2019-12-10 17:27 UTC
Labels: bug
