### ISSUE TITLE
Web page layout breaks down on HTML

### ISSUE THREAD

**Issue by Pidroh** [haxeui/haxeui-core#427] opened 2021-10-31 04:15 UTC
The page break down like the photos below:

https://imgur.com/a/bDfUuoc

The normal behavior is on the third photo.
This happens sometimes, not sure on what the trigger is, possibly an exception or me accessing something I shouldn't.
I think last time it happened I was accessing html text in the Label component. Deleting main.js and regenerating it will magically solve the problem sometimes.

No exceptions happen during this. Both in the haxe compiler and in the web browser console.

## Expected Behavior
The page should show normally according to the third picture https://imgur.com/a/bDfUuoc

## Current Behavior
The page behaves like the first two pictures https://imgur.com/a/bDfUuoc

## Possible Solution
I have no idea. Maybe if I changed by backend to kha this would go away.

## Steps to Reproduce (for bugs)

I have no idea... 
Generated source code: https://drive.google.com/file/d/1pUhu6FT2pRH5EG4u7HUvG4-r7-2_IhXo/view?usp=sharing

Some clues I have:
- usually I try to examine the source files of haxe ui core when I'm doing it. I just open the file without modifying it. I have this feeling that this usually is coupled with this issue.

## Media
https://imgur.com/a/bDfUuoc

## Test app / minimal test case
Since I can't cause it when I want to, all I have is my whole app, with generated codes with the bug and without the bug.
Source code: https://drive.google.com/file/d/1pUhu6FT2pRH5EG4u7HUvG4-r7-2_IhXo/view?usp=sharing

## Context
I want to show normal webpages always, both in development and to users, but the page breaks down, wasting development time and making it impossible for users to play when it happens there.

## Your Environment

Source code: https://drive.google.com/file/d/1pUhu6FT2pRH5EG4u7HUvG4-r7-2_IhXo/view?usp=sharing

bin.zip is the working files. bin_copy.zip is the one with the bug.
Deleting the generated main.js file and then regenerating will sometimes make the problem go away. Since that is a temporary solution I was going to live with it but a similar issue started appearing in user machines, so I need to investigate the issue I sometimes generate in my machine to get closer to the heart of the issue. But really, any clues as to how to handle this will be super helpful. Even if switching to something like KHA will make the whole thing more stable.

* Version used: 
  - haxeui-core: [1.2.3]
  - haxeui-html5: [1.2.3]
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chome Version 95.0.4638.54 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop, Windows 10 Pro 21H1
* Link to your project: https://github.com/Pidroh/HaxeRPGUtilities

**Comment by Pidroh** [comment] 2021-10-31 04:22
Just realized I should have made this in HTML, sorry!

I decided to investigate the whole thing with me opening source files in the haxe ui core. And yes, opening those files, without changing them, will break the code.

What is up with that? :(((

**Comment by Pidroh** [comment] 2021-10-31 04:22
Let me know if I should close and reopen on HTML

**Comment by ianharrigan** [comment] 2021-10-31 07:23
Its fine where it is - dont worry. Im not sure i really understand the issue though - whats the conditions where it breaks?

**Comment by Pidroh** [comment] 2021-10-31 09:23
I am having trouble explaining because I don't understand it 100% percent.

I am using Visual Studio Code, Haxe and Haxe UI. I am building for HTML. Sometimes I will open haxe UI core source codes through visual studio code F12 key. For example, I'll take a look at Button.hx to see how text works there. Then I close the code and build my project. Sometimes this will completely break the layout of my page as in the first two photos.

Sorry about the permissions on the file, you should have permissions to access the files now.

**Comment by Pidroh** [comment] 2021-10-31 09:26
It feels more like the Haxe compiler is changing the haxe ui core generated files and corrupting them somehow...

**Comment by ianharrigan** [comment] 2021-10-31 12:04
If you compile from the command line does it work every time? It might be that visual studio is screwing up (well, the haxe language server inside VSC anyway).

**Comment by Pidroh** [comment] 2021-10-31 22:47
Just tested and indeed, it works from the command line!

Okay, guess I can handle it better now! Is there any info I can give you to fix it or is just something we should let go?

My users are having a similar layout breakdown issue but they are not compiling anything... So I guess it's unrelated to this issue. Never the less, hoping you have some advice. Do you think KHA HaxeUI has changes to be more stable than HTML5 HaxeUI in that sense?

**Comment by ianharrigan** [comment] 2021-11-01 06:54
So yeah, the problem is that language server doesnt work well with complex macro type projects (like haxeui). I wonder if this would help? (from another user on the haxeui discord):

```
I was having a lot of macro-related compiler errors in haxeui... but I "fixed" it by just disabling the compilation server in VScode
I know it's been brought up before, and it doesn't seem like an easy thing to fix. But man I could not compile twice in a row without an error
In my settings.json, I put "haxe.enableCompilationServer": false and that's it. Hope that helps someone else
Your compiles will be a second slower but you won't waste 30 seconds crashing and restarting the compilation server anyway
And you keep macro'd code completion, since that's a separate thing
```

> Do you think KHA HaxeUI has changes to be more stable than HTML5 HaxeUI in that sense?

They are both very stable, haxeui-html5 moreso i would say (though haxeui-kha has also been stable for quite a while too)

**Comment by ianharrigan** [comment] 2022-09-19 08:51
Im going to close this (if thats OK? If not feel free reopen)

**Closed by ianharrigan** 2022-09-19 08:51 UTC
